### ISSUE TITLE
Investigate torii crashes

### ISSUE THREAD

**Issue by edisontim** [The-Overlore/lore-machine#28]
This happens when letting torii run for a long time: 
```
Uncaught failed to build client: status: Internal, message: "error returned from database: (code: 1) no such table: worlds", details: [], metadata: MetadataMap { headers: {"content-length": "0", "content-type": "application/grpc-web+proto"} }
```
Torii hasn't crashed, it just has an issue with its database

**Comment by edisontim** [comment]
This hasn't been happening to me for a while since the rebase on top of the official 0.3.0. 
Has this been happening to you @cwastche ?

**Comment by cwastche** [comment]
> This hasn't been happening to me for a while since the rebase on top of the official 0.3.0. Has this been happening to you @cwastche ?

I haven't gotten crashes either for some time indeed. However the lore-machine container does not run anymore either for me. Could that be the cause ?

**Comment by edisontim** [comment]
Will close this issue then, can you create a new one for lore-machiner container with logs if you have some please :) ?
