### ISSUE TITLE
experiment with actantial component of prompt to include small petty drama along with realm drama

### ISSUE THREAD

**Issue by jobez** [The-Overlore/lore-machine#7]
In reviewing the mock data: https://github.com/The-Overlore/lore-machine/pull/6#discussion_r1425606277

Currently we have this line referencing the greimas model: 
https://github.com/The-Overlore/lore-machine/pull/4/files#diff-b77c6d227ba356a187dd97b931f0999f2307a5f96feeab46d299a05c18b55541R45

We use 'soap opera like plot', but I would like to experiment a bit more where we have mixed in some personal plotlines along with the realm-level plotline. 

```
Use the greimas actantial model to put any of the characters in a role in a soap opera like plot that exists on two levels: their concern for the realm as a whole and their own interpersonal lives.
```

**Comment by edisontim** [comment]
Can this be closed?

**Comment by jobez** [comment]
id like to expeirment w/ the prompt when time permits along these lines still, if thats ok :)

**Comment by edisontim** [comment]
Of course, better prompt is always better
