### ISSUE TITLE
Specify "Lords" as a currency to the LLM

### ISSUE THREAD

**Issue by cwastche** [The-Overlore/lore-machine#71]
Otherwise, we get something like this:

2024-02-21 16:20:19,140 - overlore - DEBUG - ______User prompt______
My realm is in the order of power.
NPCS:
"""Nancy, a female farmer.
James, a male miner.
Lisa, a female miner.
Daniel, a male miner.
Paul, a male farmer.""".
Here is the most interesting event for my realm (lel Kúbklor):
"""event: Trade happened: between Nenne and lel Kúbklor realms. Nenne will get 1 Wood. lel Kúbklor will get 1 Lords. """.

________________________
2024-02-21 16:20:19,140 - overlore - DEBUG - ______GPT answer______
Dialogue Start:
Nancy: "What do you all think about this trade? Seems like we got the short end of the stick."
James: "I heard that the Lords from Nenne are supposed to bring with them some kind of ancient knowledge."

Lisa: "But we have plenty of wood, why trade it for a single Lord? Do they possess some kind of magic?"
Daniel: "Trade's a start, but I'm concerned about the balance of power. Bringing in a Lord could shift things."

Paul: "We might look beyond wood or Lords. What if this alliance brings us some hidden benefits, like new farming techniques?"
Nancy: "Or maybe an ill wind. Last night I dreamt of a storm coming, the kind that could ruin harvests."

James: "A storm? Are you sure it's not just an old wives' tale, Nancy?"
Lisa: "Wait, look yonder! The sky darkens unnaturally fast. Nancy's premonition might be upon us!"

Daniel: "All the more reason to stick together. If this Lord has wisdom, perhaps they can help us weather the storm."
Paul: "Let's hope their wisdom is as plentiful as our wood then. Else, we've made a deal with disaster."

**Comment by edisontim** [comment]
Done
