### ISSUE TITLE
bug: NPC doesn't get properly deleted from npc_spawn_db

### ISSUE THREAD

**Issue by edisontim** [The-Overlore/lore-machine#88]
Sometimes the NPC doesn't get deleted well from the DB when the event from torii is received. So the next time a user asks to spawn an NPC he gets the same, this cannot happen in a production environment as the two NPCs will then be on-chain until the end of time.

We should fix this and just in case have an <ins>owner only</ins> function in the smart contracts that `kills off` an NPC in case a bug like that happens

**Comment by edisontim** [comment]
Regarding the `kills off` npc, we can delete an entity from the executor contract if we're owner (or writer as well, not sure about that), so no need for it :)

**Comment by cwastche** [comment]
Fixed by #89 
The delete query statement was not being committed properly
